import type { ReviewSession, ReviewConfig, Severity } from "@core/config";
import { SEVERITY_EMOJI, VERSION } from "@core/config";

function countBySeverity(
  issues: { severity: Severity }[]
): Record<Severity, number> {
  const counts: Record<Severity, number> = {
    critical: 0,
    warning: 0,
    info: 0,
    nitpick: 0,
  };
  for (const issue of issues) {
    counts[issue.severity]++;
  }
  return counts;
}

export function generatePrReviewMarkdown(
  session: ReviewSession,
  config: ReviewConfig
): string {
  const now = new Date().toISOString();
  const activeIssues = session.issues.filter((i) => !i.ignored);
  const severityCounts = countBySeverity(activeIssues);

  let md = `# Code Review Report\n\n`;
  md += `**Branch:** ${session.branch}\n`;
  md += `**Date:** ${now}\n`;
  md += `**Files reviewed:** ${session.selectedFiles.length}\n`;
  md += `**Model:** ${config.model}\n\n`;

  // Summary table
  md += `## Summary\n\n`;
  md += `| Severity | Count |\n|----------|-------|\n`;
  for (const sev of ["critical", "warning", "info", "nitpick"] as Severity[]) {
    if (severityCounts[sev] > 0) {
      md += `| ${SEVERITY_EMOJI[sev]} ${sev.toUpperCase()} | ${severityCounts[sev]} |\n`;
    }
  }
  if (activeIssues.length === 0) {
    md += `| \u2705 | No issues found |\n`;
  }
  md += `\n`;

  // Files reviewed
  md += `## Files Reviewed\n\n`;
  for (const f of session.selectedFiles) {
    md += `- \`${f}\`\n`;
  }
  md += `\n`;

  // Issues by severity
  for (const sev of ["critical", "warning", "info", "nitpick"] as Severity[]) {
    const sevIssues = activeIssues.filter((i) => i.severity === sev);
    if (sevIssues.length === 0) continue;

    md += `## ${SEVERITY_EMOJI[sev]} ${sev.charAt(0).toUpperCase() + sev.slice(1)} Issues\n\n`;

    for (const issue of sevIssues) {
      md += `### ${issue.category}: ${issue.title}\n`;
      md += `**File:** \`${issue.file}\``;
      if (issue.lineRange) {
        md += ` (lines ${issue.lineRange.start}${issue.lineRange.end ? `-${issue.lineRange.end}` : ""})`;
      }
      md += `\n\n`;
      md += `${issue.description}\n\n`;
      if (issue.suggestion) {
        md += `**Suggestion:** ${issue.suggestion}\n\n`;
      }
      md += `---\n\n`;
    }
  }

  // Discussion notes
  const chatMessages = session.chatHistory.filter(
    (m) => m.role === "user" || m.role === "assistant"
  );
  if (chatMessages.length > 0) {
    md += `## Discussion Notes\n\n`;
    for (const msg of chatMessages) {
      if (msg.role === "user") {
        md += `> **You:** ${msg.content}\n\n`;
      } else {
        md += `${msg.content}\n\n`;
      }
    }
  }

  md += `---\n*Generated by review-ai v${VERSION}*\n`;

  return md;
}
